#!/usr/bin/env bash
# Render ansible/inventory/hosts.yml from `terraform output -json`.
# Run from anywhere; resolves paths relative to the repo root.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TF_DIR="${REPO_ROOT}/terraform/gcp"
INVENTORY="${SCRIPT_DIR}/hosts.yml"

if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq is required (brew install jq)" >&2
  exit 1
fi

NODES_JSON="$(terraform -chdir="${TF_DIR}" output -json nodes 2>/dev/null || true)"
if [ -z "${NODES_JSON}" ] || [ "${NODES_JSON}" = "null" ]; then
  echo "ERROR: 'terraform -chdir=${TF_DIR} output -json nodes' returned nothing." >&2
  echo "       Did you run 'make apply' (or 'terraform -chdir=${TF_DIR} apply')?" >&2
  exit 1
fi

SSH_USER="$(terraform -chdir="${TF_DIR}" output -raw ssh_user 2>/dev/null || echo crdb)"

{
  echo "# Generated by ansible/inventory/render.sh — do not edit by hand."
  echo "# Re-run after terraform apply / nodes.tf changes."
  echo "all:"
  echo "  children:"
  echo "    cockroachdb:"
  echo "      hosts:"
  echo "${NODES_JSON}" | jq -r --arg user "${SSH_USER}" '
    to_entries
    | sort_by(.key)
    | .[]
    | "        crdb-\(.key):\n" +
      "          ansible_host: \(.value.external_ip)\n" +
      "          ansible_user: \($user)\n" +
      "          ansible_python_interpreter: /usr/bin/python3\n" +
      "          private_ip: \(.value.internal_ip)\n" +
      "          crdb_locality_label: \(.value.locality_label)\n" +
      "          crdb_gce_zone: \(.value.gce_zone)" +
      ( if .value.dns_name == "" then "" else "\n          crdb_dns_name: \(.value.dns_name)" end )
  '
} > "${INVENTORY}"

echo "Wrote ${INVENTORY}"

# --- group_vars/all.yml ---------------------------------------------------
# Terraform-controlled values that need to reach Ansible.
GROUP_VARS_DIR="${SCRIPT_DIR}/group_vars"
GROUP_VARS_FILE="${GROUP_VARS_DIR}/all.yml"
GROUP_VARS_JSON="$(terraform -chdir="${TF_DIR}" output -json ansible_group_vars 2>/dev/null || echo '{}')"

mkdir -p "${GROUP_VARS_DIR}"
{
  echo "# Generated by ansible/inventory/render.sh — do not edit by hand."
  echo "# Sourced from terraform output 'ansible_group_vars'."
  # tojson emits each value as JSON, which is valid YAML — handles strings,
  # numbers, lists, and nested objects uniformly.
  echo "${GROUP_VARS_JSON}" | jq -r 'to_entries | .[] | "\(.key): \(.value | tojson)"'
} > "${GROUP_VARS_FILE}"

echo "Wrote ${GROUP_VARS_FILE}"
echo
cat "${INVENTORY}"
echo
echo "--- group_vars/all.yml ---"
cat "${GROUP_VARS_FILE}"
